[phases.setup]
nixPkgs = ['bun']
aptPkgs = ['build-essential', 'openssl', 'libssl-dev']

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = [
  "bunx prisma generate",  
  "bun run build"
]

[start]
cmd = "bun run start"
