[phases.setup]
nixPkgs = ['openssl_3', 'pkg-config', 'glibc']
aptPkgs = ['libssl-dev']

[phases.install]
cmds = [
  "bun install"
]

[phases.build]
cmds = [
  "bunx prisma generate",
  "bun run build"
]

[start]
cmd = "bun run start"
